config/routes.rb
SynergyCroatia::Application.routes.draw do
  scope "(:locale)", locale: /en|hr/ do
    root to: "pages#news"

    controller :pages do
      get "about"
      get "news"
      get "evs"
      get "trainings"
      get "projects"
      get "testimonials"
      get "partnerships"
      get "gallery"
      get "contact"
      get "search"
    end

    get "partners" => redirect("partnerships#partners")

    resources :albums

    controller :support do
      get "donate"
      get "volunteer"
      post "volunteer", to: :create_volunteer
    end
  end
end

app/models/album.rb
class Album < ActiveRecord::Base
  has_many :photos, dependent: :destroy
  belongs_to :cover_photo, class_name: "Photo", dependent: :destroy

  acts_as_list

  after_initialize :build_cover_photo, unless: :cover_photo

  validates_presence_of :name_en, :name_hr

  default_scope -> { order{position.asc} }

  accepts_nested_attributes_for :photos, allow_destroy: true
  accepts_nested_attributes_for :cover_photo
end

app/models/page_photo.rb
class PagePhoto < ActiveRecord::Base
  mount_uploader :image, PagePhotoUploader

  DIMENSIONS = {width: 640, height: 88}

  before_destroy { false } # Forbid deletion
  before_update :initialize_cropping
  after_update { image.recreate_versions! if image.present? }

  validates_uniqueness_of :action, scope: :controller

  def self.find(uid)
    begin
      super(Integer(uid))
    rescue ArgumentError
      controller, action = uid.split("/")
      find_by(controller: controller, action: action)
    end
  end

  def to_s
    begin
      I18n.t!("#{controller}.#{action}.navigation_title")
    rescue
      I18n.t("#{controller}.#{action}.page_title")
    end
  end

  private

  ##
  # HACK: For some reason, wheb PagePhotoUploader#initialize_crop_dimensions
  # assigns the "crop_<attr>" columns, these columns somehow later get
  # deassigned (god knows what sorcery happens in the callbacks). So here in
  # the model we assign them again (just duplicate the method).
  #
  def initialize_cropping
    if crop_x.blank?
      image_matrix = ::Magick::Image.read(image.file.file).first
      original_width, original_height = image_matrix.columns, image_matrix.rows

      w = DIMENSIONS[:width]
      h = (DIMENSIONS[:height] * w) / DIMENSIONS[:width]
      x = 0
      y = (original_height / 2) - (h / 2)

      self.crop_x = x
      self.crop_y = y
      self.crop_w = w
      self.crop_h = h
    end
  end
end

app/models/partner.rb
require "squeel"

class Partner < ActiveRecord::Base
  mount_uploader :photo, PartnerPhotoUploader
  required_locale_columns :name, :url, validations: false
  acts_as_list

  validates_presence_of :name_en, :name_hr, :photo, :url_en, :url_hr

  default_scope         -> { order{position.asc} }
  scope :local,         -> { where{kind == "local"} }
  scope :international, -> { where{kind == "international"} }
end

app/models/photo.rb
require "pathname"

class Photo < ActiveRecord::Base
  belongs_to :album

  mount_uploader :image, PhotoUploader

  default_scope -> { order{created_at.asc} }

  validates_presence_of :image

  def present?
    image.present?
  end

  def url(*args)
    image.url(*args)
  end

  def title
    filename = Pathname.new(image.file.filename)
    filename.basename(filename.extname)
  end
end

app/models/training.rb
class Training < ActiveRecord::Base
  belongs_to :category
  has_many :testimonials, dependent: :destroy

  serialize :participating_countries

  default_scope order("trainings.ends_on DESC")
  scope :upcoming, where("trainings.ends_on >= current_date")
  scope :forecoming, where("trainings.ends_on < current_date")

  def training?
    category != Category.find_by_name_en("Youth Exchange")
  end

  def exchange?
    category == Category.find_by_name_en("Youth Exchange")
  end

  if Rails.env.development?
    has_attached_file :infoletter
    has_attached_file :application_form
  else
    has_dropbox_file :infoletter
    has_dropbox_file :application_form
  end

  translates :description
  translates :summary
  translates :expenses
  translates :city

  def duration
    (ends_on - begins_on).to_i + 1
  end

  def to_s
    title
  end
end

app/models/volunteer.rb
require "active_attr"

class Volunteer
  include ActiveAttr::Model

  attribute :name
  attribute :profession
  attribute :age
  attribute :email
  attribute :phone
  attribute :interests
  attribute :reason
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def show
    @album = Album.find(params[:id]).decorate
  end
end

app/controllers/application_controller.rb
class ApplicationController < SynergyController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def news
    @news = News.all
      .map(&:decorate)
      .paginate(page: params[:page], per_page: 3)
  end

  def about
  end

  def evs
  end

  def projects
    @projects = Project.available_in(I18n.locale)
    @projects = @projects.search(params[:q]) if params[:q]
    @projects = @projects.decorate.paginate(page: params[:page], per_page: 3)
  end

  def archive
    @projects = Project
      .forecoming
      .order(begins_on: :desc)
      .paginate(page: params[:page], per_page: 10)
      .decorate
  end

  def testimonials
    @testimonials = Testimonial
      .order{created_at.desc}
      .available_in(I18n.locale)
      .paginate(page: params[:page], per_page: 1)
      .decorate
  end

  def partnerships
    body = @text.object.send(:"body_#{I18n.locale}")
    body << view_context.render("partners", partners: Partner.local.decorate, kind: "local")
    body << view_context.render("partners", partners: Partner.international.decorate, kind: "international")
  end

  def gallery
    @albums = Album.decorate
  end

  def contact
  end

  def search
    @results = PgSearch.multisearch(params[:q])
  end
end

app/controllers/support_controller.rb
class SupportController < ApplicationController
  def donate
  end

  def volunteer
    @volunteer = Volunteer.new
  end

  def create_volunteer
    @volunteer = Volunteer.new
    @volunteer.assign_attributes(volunteer_params)

    if @volunteer.valid?
      VolunteeringMailer.volunteer(@volunteer)
      redirect_to root_path, notice: "Vaša prijava je poslana, uskoro ćemo vam se javiti. Hvala."
    else
      render :volunteer
    end
  end

  private

  def volunteer_params
    params.require(:volunteer).permit!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def navigation_pages
    pages = %w[news about trainings projects partnerships evs gallery contact]
    pages.delete("gallery") if Album.count == 0
    pages.collect do |name|
      {
        title: (I18n.t!("pages.#{name}.navigation_title") rescue t("pages.#{name}.page_title")),
        path: {controller: "pages", action: name},
      }
    end
  end

  def title(value)
    content_tag :h1, style: ("background-image: url(#{@page_photo.image.url(:display)})" if @page_photo) do
      value
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/support_helper.rb
module SupportHelper
  def interests
    [
      [t(".interest_1")],
      [t(".interest_2")],
      [t(".interest_3")],
      [t(".interest_4")],
    ]
  end
end

app/views/admin/categories/_form.haml
- url = @category.new_record? ? admin_categories_path : admin_category_path(@category)

= simple_form_for @category, url: url, defaults: {locale: :hr} do |f|

  = f.error_notification

  = f.input :name_hr
  = f.input :name_en

  .form_actions
    = cancel_button "Odustani", (referer || admin_categories_path)
    = f.button :submit, class: "btn_primary"

app/views/admin/categories/edit.haml
- @title = "Izmjena tipa kategorije"

%p= back_button "Natrag", admin_categories_path

= render "form"

app/views/admin/categories/index.haml
- @title = "Tipovi projekata"

%p= add_button "Novi tip projekta", new_admin_category_path

= render partial: "categories/category", collection: @categories

app/views/admin/categories/new.haml
- @title = "Novi tip projekta"

= render "form"

app/views/admin/page_photos/_form.html.haml
= simple_form_for [:admin, @page_photo], defaults: {wrapper_tag: :li} do |f|

  %fieldset.inputs
    %ol
      = f.input :image

    - if @page_photo.persisted?

      = image_tag @page_photo.image.url, id: "cropbox"

      - %w[x y w h].each do |attribute|
        = f.hidden_field "crop_#{attribute}"

  %fieldset.actions
    %ol
      %li= f.button :submit
      %li.cancel= link_to "Cancel", resource_path

app/views/admin/projects/_form.haml
- url = @project.new_record? ? admin_projects_path : admin_project_path(@project)

= simple_form_for @project, url: url, defaults: {locale: :hr} do |f|

  .inner
    = f.input :name_en
    = f.input :name_hr
    = f.input :category do
      = f.association :category, prompt: "Odaberi…", wrapper: false, label: false
      %p ili stvori #{link_to "novi", new_admin_category_path}.
    = f.input :country, priority: common_countries
    = f.input :city_hr
    = f.input :city_en
    = f.input :begins_on
    = f.input :ends_on
    = f.input :description_hr, input_html: {class: "big"}
    = f.input :description_en, input_html: {class: "big"}
    = f.input :summary_hr
    = f.input :summary_en
    = f.input :participating_countries, priority: common_countries, multiple: true, size: 10
    = f.input :age_restriction do
      #{f.number_field(:minimum_age)} – #{f.number_field(:maximum_age)}
    = f.input :infoletter
    = raw "Trenutno učitano: #{uploaded_file(@project.infoletter, "Infoletter")}" if @project.infoletter?
    = f.input :application_form
    = raw "Trenutno učitano: #{uploaded_file(@project.application_form, "Prijavnica")}" if @project.application_form?
    = f.input :deadline
    = f.input :available_space

  .form_actions
    = cancel_button "Odustani", admin_projects_path
    = f.button :submit, class: "btn_primary"

app/views/admin/projects/edit.haml
- @title = "Izmjena projekta"

%p= back_button "Natrag", admin_projects_path

= render "form"

app/views/admin/projects/index.haml
- @title = "Projekti"

%p= add_button "Novi projekt", new_admin_project_path

= render partial: "projects/project_long", collection: @projects, as: :project

= will_paginate @projects

app/views/admin/projects/new.haml
- @title = "Novi projekt"

%p= back_button "Natrag", admin_projects_path

= render "form"

app/views/announcements/_announcement.haml
- present announcement do |announcement_presenter|

  - if admin?
    .controls
      = announcement_presenter.edit_button "", title: "Izmjeni"
      = announcement_presenter.delete_button "", title: "Izbriši"

  %dl
    %dt.hr Sadržaj
    %dd= announcement_presenter.content_hr

    %dt.en Sadržaj
    %dd= announcement_presenter.content_en

    %dt Istječe
    %dd= announcement_presenter.expires_on

app/views/categories/_category.haml
- present category do |category_presenter|

  - if admin? and category.not_in?(forbidden_categories)
    .controls
      = category_presenter.edit_button ""
      = category_presenter.delete_button ""

  %dl
    %dt.hr Naziv
    %dd= category_presenter.name_hr
    %dt.en Naziv
    %dd= category_presenter.name_en

app/views/pages/search/_post.html.haml
%li
  = link_to "Vijesti", news_path
  &gt;
  = link_to post.title, post

app/views/pages/search/_project.html.haml
%li
  = link_to "Vijesti", news_path
  &gt;
  = link_to project.name, project

app/views/pages/search/_text.html.haml
- text.parts.each do |part|
  - if part.title =~ /#{params[:q]}/i or part.body =~ /#{params[:q]}/i
    %li
      = link_to text.to_s, action: text.action
      - if text.toc?
        &gt;
        - if part.title
          = link_to part.title, action: text.action, anchor: part.title.parameterize
        - else
          = link_to "Općenito", action: text.action

app/views/projects/_form.haml
= simple_form_for @project do |f|

  .inner
    = f.input :category do
      = f.association :category, prompt: "Izaberi...", wrapper: false, label: false
      ili stvori #{link_to "novi", new_category_path}.
    = f.input :name
    = f.input :country, priority: common_countries
    = f.input :city_hr
    = f.input :city_en
    = f.input :begins_on
    = f.input :ends_on
    = f.input :description_hr
    = f.input :description_en
    = f.input :summary_hr
    = f.input :summary_en
    = f.input :expenses_hr
    = f.input :expenses_en
    = f.input :participating_countries, priority: common_countries, multiple: true, size: 10
    = f.input :age_restriction do
      #{f.number_field(:minimum_age)} – #{f.number_field(:maximum_age)}
    = f.input :infoletter
    = f.input :application_form
    = f.input :deadline
    = f.input :available_space

  .controls
    = cancel_button "Odustani", root_path
    = f.button :submit

app/views/projects/_project.haml
- present project do |project_presenter|

  %article{class: project.training? ? "training" : "exchange"}

    %header
      %h1= project_presenter.title
      %p.info= project_presenter.location

    = project_presenter.summary

    %p= link_to raw("Opširnije →"), project

app/views/projects/_project_long.haml
- present project do |project_presenter|

  %article.project_long.fade_out

    - if admin?
      .controls
        = project_presenter.edit_button "", title: "Izmjeni"
        = project_presenter.add_testimonial_button "", title: "Dodaj iskustvo"
        = project_presenter.delete_button "", title: "Izbriši"

    - if admin?
      %h1.title= project_presenter.title

    - unless admin?
      %p.location= project_presenter.location.prepend_icon("location")

      = project_presenter.description

      %ol.attachments
        = content_tag :li, project_presenter.infoletter("Infoletter") if project_presenter.infoletter?
        = content_tag :li, project_presenter.application_form("Prijavnica") if project_presenter.application_form?

app/views/projects/_project_short.haml
- present project do |project_presenter|

  %article.project_short

    %h2.title= project_presenter.title
    = project_presenter.summary

    %dl
      %dt= t(".location")
      %dd.location= project_presenter.location

      %dt= t(".duration")
      %dd.duration= project_presenter.duration

      %dt= t(".infoletter")
      %dd.infoletter= project_presenter.infoletter("Infoletter")

app/views/projects/edit.haml
- @title = "Izmjena projekta"

= render "form"

app/views/projects/show.haml
- @title = @project.name

%p= back_button "Natrag na projekte", news_path

= render partial: "project_long", object: @project, as: :project

app/views/shared/_footer.haml
%footer.site_footer
  .container
    %p.copyright © Syncro Synergy Croatia 2012.

app/views/shared/_header.haml
%header.site_header
  .container
    .site_logo= link_to image_tag("logo.png", alt: "logo"), root_path

    .site_quote= raw(t(".quote"))

    %ol.site_lang
      %li= link_to image_tag("lang/HR.png", size: "24x24", title: "Hrvatski"), locale: :hr
      %li= link_to image_tag("lang/GB.png", size: "24x24", title: "English"), locale: :en

    - if logged_in?
      .logged_in
        Prijavljeni ste kao administrator.
        #{link_to "Admin", admin_root_path}
        | #{link_to "Odjava".prepend_icon("exit"), logout_path, method: :delete}

app/views/shared/_javascript.haml
:javascript
  // by Paul Irish (@paul_irish)
  // turns html.no-js into html.js
  (function(H){H.className=H.className.replace(/\bno-js\b/,'js')})(document.documentElement);

  // Typekit
  (function() {
    var config = {
      kitId: "fgk3olu",
      scriptTimeout: 3000
    };
    var h=document.getElementsByTagName("html")[0];h.className+=" wf-loading";var t=setTimeout(function(){h.className=h.className.replace(/(\s|^)wf-loading(\s|$)/g," ");h.className+=" wf-inactive"},config.scriptTimeout);var tk=document.createElement("script"),d=false;tk.src='//use.typekit.net/'+config.kitId+'.js';tk.type="text/javascript";tk.async="true";tk.onload=tk.onreadystatechange=function(){var a=this.readyState;if(d||a&&a!="complete"&&a!="loaded")return;d=true;clearTimeout(t);try{Typekit.load(config)}catch(b){}};var s=document.getElementsByTagName("script")[0];s.parentNode.insertBefore(tk,s)
  })();
</script>

app/views/shared/_navigation.haml
%nav.site_navigation
  - pages = if admin then admin_navigation_pages else navigation_pages end

  .container
    %input{type: "checkbox", id: "nav_expander"}
    %label{class: "expander", for: "nav_expander"}
      = icon("menu")
      %span.current_page= current_page_title(pages)

    %ol
      - pages.each do |page|
        %li{class: ("active" if current_page?(page.route))}
          = link_to page.title, page.route

app/views/testimonials/_testimonial.haml
- present testimonial do |testimonial_presenter|

  %article{class: ("fade_out" if admin?)}
    - if admin?
      .controls
        = testimonial_presenter.edit_button "", title: "Izmjeni"
        = testimonial_presenter.delete_button "", title: "Izbriši"

    %blockquote
      = testimonial_presenter.content

      %footer
        %b.author= testimonial_presenter.author
        ,
        = testimonial_presenter.project

app/views/testimonials/index.haml
- @title = t(".page_title")

= render @testimonials

app/views/trainings/_form.haml
= simple_form_for @training do |f|

  .inner
    = f.input :category do
      = f.association :category, prompt: "Izaberi...", wrapper: false, label: false
      ili stvori #{link_to "novi", new_category_path}.
    = f.input :name
    = f.input :country, priority: common_countries
    = f.input :city_hr
    = f.input :city_en
    = f.input :begins_on
    = f.input :ends_on
    = f.input :description_hr
    = f.input :description_en
    = f.input :summary_hr
    = f.input :summary_en
    = f.input :expenses_hr
    = f.input :expenses_en
    = f.input :participating_countries, priority: common_countries, multiple: true, size: 10
    = f.input :age_restriction do
      #{f.number_field(:minimum_age)} – #{f.number_field(:maximum_age)}
    = f.input :infoletter
    = f.input :application_form
    = f.input :deadline
    = f.input :available_space

  = f.button :submit
  = cancel_button "Odustani", root_path